sudo: false
language: ruby
cache: bundler
rvm:
#- 2.1
- 2.1.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "mxMjopEDiJmO5MoZeb2Dh/UK65+hESOBzIPi7X5x1fTCapiw9T7NLyFPtVyfdp4Krok6iFwqDoGJVTc/H/HSaRUZCd+Vu+dzTSSwgSsCt8QL05VgEGvVVw2NAwmMOLSgPbwXGE/KIIAy2W1jwauo8feezTItO20rOmgSb7qjQEPdEhZFq0coR4fgAaRjD5xuTODioLgDDrFMArmmUj5fzHcQHhOyEyOsVIstEq6RkOy/EkU+FwyKD1C9eFHPmZyWA82XyE961sJxEBCgrWdQJabbRhfRgELT0o5EnhoDckHD+H3pQJvxUj3JAzGCNC8f2/HllcTXYbHtbmmRiEUq0urLgpFCYF53/KFvO4vx2Kzle77rjnpOvWCUppUF2NR4DbdCZUc1R9lswf9+d5Wpg6xGmJc+428aNghKZfbJXCfNrty429yKEgd+3ndEeyx4YiamJ58tjtlmetJ3Hh3kWL6eiARugGLOruy3SPdg+rzDV//G6rxl2ulL1FcN3grIX+CssThPKqJQsmB9T9Sto3nvHdCcOYtoFenTH6fuvoNDjA8u7MJiZ3R1WQBhR4MqblgkMA3gkCtw4sYsFbFarEIZ81JKpMa2xTD+QFtGIOy5tDqrduN/gN/roWWSzcDj/xLBlWJIGJjQM9WHDjquTTdegoEbPgqoqNHqN1hShAY="
branches:
  only:
    - master
